# Generated by Django 4.2.13 on 2024-07-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_familymember_remove_relationship_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
