# Generated by Django 4.2.13 on 2024-07-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_familymember_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='death_date',
        ),
        migrations.AddField(
            model_name='familymember',
            name='child_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
