# Generated by Django 4.2.13 on 2024-07-05 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0005_remove_familymember_death_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spouse_members', to='tree.familymember'),
        ),
    ]
