# Generated by Django 4.2.13 on 2024-07-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0006_familymember_spouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={'ordering': ['child_number', 'name']},
        ),
    ]
