# Generated by Django 4.2.13 on 2024-07-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0007_alter_familymember_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={'ordering': ['name', 'child_number']},
        ),
    ]
